---
title: "Corona virus map"
author: "Steve Simon"
date: "3/9/2020"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE)
# install.packages("rnaturalearthhires", repos="http://packages.ropensci.org", type="source")
suppressMessages(suppressWarnings(library(lubridate)))
suppressMessages(suppressWarnings(library(mapproj)))
suppressMessages(suppressWarnings(library(rgeos)))
suppressMessages(suppressWarnings(library(rjson)))
suppressMessages(suppressWarnings(library(rnaturalearth)))
suppressMessages(suppressWarnings(library(rnaturalearthdata)))
suppressMessages(suppressWarnings(library(sf)))
suppressMessages(suppressWarnings(library(stringr)))
suppressMessages(suppressWarnings(library(tidyverse)))
```



```{r}
ne_states(country="United States of America", returnclass = "sf") %>%
  filter(postal != "HI" & postal != "AK") -> states
world1 <- ne_countries(scale = "medium", returnclass = "sf")
continental_us <- ggplot() + geom_sf(data = states)
```


```{r}
projection_string <- "+proj=laea +lon_0=-100 +lat_0=40 +ellps=WGS84 +no_defs"
states %>%
  filter(name_en=="Colorado") %>%
  ggplot() + 
  geom_sf() + 
  coord_sf(crs=projection_string)
```

### Read the files


```{r ts}
fn <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
read.csv(fn, stringsAsFactors=FALSE) %>%
  st_as_sf(coords=c("Long", "Lat")) -> raw_data_ts
```

```{r}
fn <- "https://raw.githubusercontent.com/beoutbreakprepared/COVID-19-data-mapping-pipeline/master/ncov2019.unique-locations.json"
raw_data_ts <- readLines(fn)
pull_fields <- function(raw_data, field_name) {
  raw_data %>%
    str_subset(field_name) %>%
    str_remove_all("^.*: ") %>%
    str_remove_all('"') %>%
    str_remove_all(",")
}
raw_data_ts[1:100] %>%
  pull_fields("latitude") %>%
  as.numeric %>%
  data.frame %>%
  set_names("lat")
```

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
states <- ne_states(country="United States of America", returnclass = "sf")
```

```{r}
long.lat.range <- c(-130, -65, 24, 51); region_filter <- raw_data_ts$Country.Region=="US"
long.lat.range <- c(-180, 180, -90, 90)
raw_data_ts %>%
  filter(region_filter) -> restricted_ts
```

```{r}
last_date <- dim(raw_data_ts)[2]-1
date_names <- str_sub(names(raw_data_ts)[5:last_date], 2)
```

```{r}
i <- last_date
  circle_size <- sqrt(restricted_ts[ , i])
  # if (sum(circle_size)==0) next
  non_zero_cases <- circle_size>0
  ggplot(data = states) +
    geom_sf(color="gray", fill="white") +
    geom_sf(
      data=restricted_ts[non_zero_cases, ],
      size=circle_size[non_zero_cases],
      color="darkorange", alpha=0.5)  +
    coord_sf(xlim = long.lat.range[1:2], ylim = long.lat.range[3:4], expand = FALSE) +
      ggtitle(date_names[i-4], sum(restricted_ts[ , i])) -> filtered_plot
  plot(filtered_plot)
```
