---
title: "M02. Overview of module02"
author: "Steve Simon"
output: html_document
---

This document was created on 2020-02-13 and last modified on `r format(Sys.Date(), "%Y-%m-%d")`. It is written in RMarkdown and run with `r R.version.string`.

This module discusses how to handle datasets that have mostly continuous variables. These are the simplest datasets and represent a reasonable starting point. 

## Learning objectives

In these videos you will learn

+ how to print all or part of a data frame
+ create a missing value code
+ find and account for missing values
+ produce histograms and scatterplots

## Videos

There are five videos in this module specific to the R programming language and two general videos about good programming practices.

+ V02-01. Rmarkdown structure
+ V02-02. Outliers and missing values
+ V02-03. Histograms
+ V02-04. Correlations and scatterplots
+ V02-05. Description of sleep data
  + The slides and speaker notes for these five videos can be found [here](http://www.pmean.com/introduction-to-r/results/v02-slides-and-speaker-notes.pdf).
+ General video. Data dictionary
+ General video. Good computing practices, part 1
  + The slides and speaker notes for these videos are not yet available.

You can find links to the videos on the Canvas website.

## Datasets used in this module

There are three datasets used in this module. All of these are stored in a single binary file, which you can download [here](../data/module02-datasets.RData). You should not need the text versions of the files, but I am including links to them below.

### bump

+ View the [data dictionary](../data/airline-data-dictionary.txt)
+ Used in the video
+ Not needed for the homework assignment
+ A [text version](../data/airline-bumping-2017.txt) of this dataset.

### fd

+ View the [data dictionary](../data/fat-data-dictionary.txt)
+ Used in the video
+ Not needed for the homework assignment
+ A [text version](../data/fat.txt) of this dataset.

### sleep

+ View the [data dictionary](../data/sleep-data-dictionary.txt)
+ Not used in the video
+ You will need this dataset for the homework assignment
+ A [text version](../data/sleep.txt) of this dataset.

## Assignments

### D02-01. Feedback after viewing videos

Graded: 3 points, one point deduction if submitted after the due date.

Review the videos in this section and answer the following questions.

1. What was the most important thing you learned.

2. What did you find confusing.

3. What would you like to see covered next.

It is okay to use short answers like "Nothing was confusing" or "Everything was confusing." You can also briefly concur with a previous student's comments.

### HW02. Read in and analyze the sleep data.

Graded: 3 points, one point deducted if submitted late.

Download the the file [module02-datasets.RData](../data/module02-datasets.RData) and store it in the appropriate folder. Then run a program using Rmarkdown to answer the following questions.

Include both the question and your answer to the question in the Rmarkdown code. Submit your work as a single PDF file.

If there are errors or warnings in your output, send me PDF files of your code and your output by email and I will see if I can help.

Q1. Notice that there is a huge range in body weight. Display the information for the smallest and the largest mammals.

Q2. Which variables have missing data?

Q3. Calculate the mean and standard deviation for TotalSleep.

Q4. Do bigger animals sleep longer or live longer? Show your results using a correlation coefficient.

Q5. Do animals who have high degrees of Predation, Exposure, or Danger sleep less? Show your results using a plot and a trendline.
