---
title: "M03. Overview of module03"
author: "Steve Simon"
output: html_document
---

## Introduction

This document was created on 2020-03-02 and last modified on `r format(Sys.Date(), "%Y-%m-%d")`. It is written in RMarkdown and run with `r R.version.string`.

This is an overview of module03, which discusses how to read and write text files in R. Parts of it are posted in various locations on the Canvas website. If you notice a discrepancy between this overview and the Canvas website, please notify me. The Canvas website always takes precedence.

## Synopsis

Text data comes in a variety of shapes and forms. This module will show you how to read files with delimiters and fixed width files.

## Videos

There is one video in this module specific to the R programming language and two general videos about good programming practices. You can find links to the videos on the Canvas website.

+ V03-01. Reading and writing text files
  + The slides and speaker notes for this video can be found [here](http://www.pmean.com/introduction-to-r/results/v03-slides-and-speaker-notes.pdf).+ + Good computing practices, part 2
+ Good computing practices, part 3
  + The slides and speaker notes for these videos are not yet available.

You can find links to the videos on the Canvas website.

## Datasets used in this module

I will not be providing a data dictionary for the small artifical dataset with four rows that appears in a variety of formats.

### ED2017

+ View the [data dictionary](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NHAMCS/doc17_ed-508.pdf)
+ Used very briefly in the video.
+ Not needed for the homework assignment
+ A [text version](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/NHAMCS/ED2017.zip) of this dataset.

### Binary

+ There is no data dictionary, but a brief description is found buried on [this page](https://stats.idre.ucla.edu/r/dae/logit-regression/).
+ Used in the video.
+ Not needed for the homework assignment
+ A [text version](https://stats.idre.ucla.edu/stat/data/binary.csv) of this dataset.

### Barbershop music

+ View the [data dictionary](https://dasl.datadescription.com/datafile/barbershop-music/)
+ Used in the video.
+ Not needed for the homework assignment
+ A [text version](https://dasl.datadescription.com/download/data/3061) of this dataset.

### Airport

+ View the [data dictionary](http://jse.amstat.org/datasets/airport.txt)
+ Used in the video.
+ Not needed for the homework assignment
+ A [text version](http://jse.amstat.org/datasets/airport.dat.txt) of this dataset.

### Oyster

+ View the [data dictionary](http://jse.amstat.org/datasets/30oysters.txt)
+ You need this data for the homework assignment
+ A [text version](http://jse.amstat.org/datasets/30oysters.dat.txt) of this dataset.

### Snails

+ View the [data dictionary](https://dryad.figshare.com/articles/Susceptibility_of_live_snails_to_predation/4114368)
+ You need this data for the homework assignment
+ A [text version](https://dryad.figshare.com/ndownloader/files/6668235) of this dataset.

### Diamond rings

+ View the [data dictionary](http://jse.amstat.org/datasets/diamond.txt)
+ You need this data for the homework assignment
+ A [text version](http://jse.amstat.org/datasets/diamond.dat.txt) of this dataset.

## Assignments

### D03-01. Feedback after viewing videos

Graded: 3 points, one point deduction if submitted after the due date.

Review the videos in this section and answer the following questions.

1. What was the most important thing you learned.

2. What did you find confusing.

3. What would you like to see covered next.

It is okay to use short answers like "Nothing was confusing" or "Everything was confusing." You can also briefly concur with a previous student's comments.

### HW03. Read in two different text files.

Graded: 3 points, one point deducted if submitted late.

`r readLines("../data/hw0301.txt")`

`r readLines("../data/hw0302.txt")`

`r readLines("../data/hw0303.txt")`

