---
title: "M01. Overview of module01"
author: "Steve Simon"
output: html_document
---

## Introduction

This document created on 2020-03-30 and was last modified on `r format(Sys.Date(), "%Y-%m-%d")`. It is written in RMarkdown and run with `r R.version.string`.

This is an overview of module06, which discusses how to get started with R. Parts of it are posted in various locations on the Canvas website. If you notice a discrepancy between this overview and the Canvas website, please notify me. The Canvas website always takes precedence.

This module discusses how to handle datasets that have mostly continuous variables. These are the simplest datasets and represent a reasonable starting point.

## Synopsis

R is a programming language with lots of features useful for managing and analyzing data. It is freely available. You will learn how to download and install R as well as RStudio, an integrated development environment for R. In this class, all the work will be done using RMarkdown, a language that combines R programming statements with free-form commentary. You will see how to organize a directory structure for the files used in this class and understand the general structure of an RMarkdown file.

## Videos

There are two videos for this module. The first one is about the R programming language and the second is a general video on good programming practices.

+ V01-01. A simple program
  + The slides and speaker notes for this video can be found [here](http://www.pmean.com/introduction-to-r/results/v01-slides-and-speaker-notes.pdf).
+ General video. Good documentation
  + The slides and speaker notes for this video are not yet available.

You can find links to the videos on the Canvas website.

## Datasets used in this module

There is one dataset used in this module. It is stored in a single binary file, which you can download [here](../data/module01-datasets.RData). You should not need the text version of the file, but I am including links to them below.

### bump

+ View the [data dictionary](../data/airline-data-dictionary.txt)
+ Used in the video
+ Not needed for the homework assignment
+ A [text version](../data/airline-bumping-2017.txt) of this dataset.

## Assignments

### D01-01. Introduce yourself

Graded: 3 points, one point deduction if submitted after the deadline.

Tell us about yourself. What degree program you are in, why you are taking this class, and what you are hoping to do when you graduate.

Optionally, include a picture of yourself and tell us about one of your hobbies.

### D01-02. Feedback after viewing videos

Graded: 3 points, one point deduction if submitted after the due date.

Review the videos in this section and answer the following questions.

1. What was the most important thing you learned.

2. What did you find confusing.

3. What would you like to see covered next.

It is okay to use short answers like "Nothing was confusing" or "Everything was confusing." You can also briefly concur with a previous student's comments.

### HW01. Adapt the small program to run on your computer.

Graded: 3 points, one point deducted if submitted late.

Download the code for [small-program.Rmd](../src/small-program.Rmd) and the datafile two-small-dataframes.RData(../data/two-small-dataframes.RData) and store the files in a src and data directory somewhere on your computer. Modify the code so that you are listed as the author. Run the program and submit it as a PDF file.

If there are errors or warnings in your output, make your best effort to fix them, but getting anything to run, even something with error messages will be sufficient for this very first homework assignment.
