---
title: "Preparations for module02"
author: "Steve Simon"
date: "Created 2020-02-08"
output: powerpoint_presentation
---

### bump

```{r input-bump}
options(width=45)
bump <- read.table(
  "../data/airline-bumping-2017.txt", 
  header=TRUE,
  stringsAsFactors=FALSE)
```

### Test 1

```{r test1}
bump
```

### Test 2

```{r test2}
str(bump)
```

### fd

```{r input-fd}
fd <- read.table("../data/fat.txt")
names(fd) <- c(
  "case",     "fat_b",  "fat_s", 
  "density",  "age",    "wt", 
  "ht",       "bmi",    "ffw", 
  "neck",     "chest",  "abdomen", 
  "hip",      "thigh",  "knee", 
  "ankle",    "biceps", "forearm", 
  "wrist"
)
```

### Test 3

```{r test3}
head(fd, 2)  
```

### Test 4

```{r test4}
str(fd)
```

### Input sleep

```{r input-sleep}
sleep <- read.table(
  "../data/sleep.txt",
  stringsAsFactors=FALSE,
  header=TRUE,
  sep="\t"
)
```

### Test 5

```{r test5}
head(sleep, 2)
```

### Test 6

```{r test6}
str(sleep)
```
### Save everything

```{r save}
save(bump, fd, sleep, file="../data/module02-datasets.RData")
```


